apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-curl-daemon
  namespace: mateapp
  labels:
    app: todoapp-curl
spec:
  selector:
    matchLabels:
      app: todoapp-curl
  template:
    metadata:
      labels:
        app: todoapp-curl
    spec:
      containers:
      - name: curl
        image: radial/busyboxplus:curl
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              curl http://todoapp:8000
              sleep 5
            done
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
